# Generated by Django 5.2.5 on 2025-08-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_type', models.CharField(choices=[('dine-in', 'Dine In'), ('parcel', 'Parcel')], default='dine-in', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('dname', models.TextField(max_length=122)),
                ('dquantity', models.IntegerField()),
                ('damount', models.IntegerField()),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=254)),
                ('dishname', models.TextField(max_length=200)),
                ('dishprice', models.IntegerField()),
                ('dishtype', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='restaurant.customer')),
            ],
            options={
                'db_table': 'restaurant_tables',
                'managed': True,
            },
        ),
    ]
