# Generated by Django 3.1 on 2025-05-22 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=254)),
                ('time', models.TextField(max_length=122)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_type', models.CharField(choices=[('dine-in', 'Dine In'), ('parcel', 'Parcel')], default='parcel', max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('dname', models.TextField(max_length=122)),
                ('dquantity', models.IntegerField()),
                ('damount', models.IntegerField()),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.EmailField(max_length=254)),
                ('dishname', models.TextField(max_length=200)),
                ('dishprice', models.IntegerField()),
                ('dishtype', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='restaurant.customer')),
            ],
            options={
                'db_table': 'restaurant_tables',
                'managed': True,
            },
        ),
    ]
