# Generated by Django 5.2.1 on 2025-05-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_table_options_alter_customer_id_alter_dish_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'managed': True},
        ),
    ]
