# Generated by Django 5.2.1 on 2025-05-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_table_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'Dine In'), ('parcel', 'Parcel')], default='dine-in', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
